-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 14:34:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) ,
  UNIQUE INDEX `uf_UNIQUE` (`uf` ASC),
  UNIQUE INDEX idEstado_UNIQUE (idEstado ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_Cidade_Estado3_idx` (`Estado_idEstado` ASC),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC),
  CONSTRAINT `fk_Cidade_Estado3`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `idBairro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Cidade_idCidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBairro`),
  UNIQUE INDEX `idBairro_UNIQUE` (`idBairro` ASC) ,
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_idCidade` ASC) ,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hospede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hospede` (
  `idHospede` INT UNSIGNED NOT NULL ,
  `nome_hospede` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NULL,
  `Bairro_idBairro` INT UNSIGNED NOT NULL,
  `CEP` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHospede`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_Hospede_Bairro1_idx` (`Bairro_idBairro` ASC) ,
  CONSTRAINT `fk_Hospede_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `mydb`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa_Fisica`;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Fisica` (
  `CPF` BIGINT NOT NULL,
  `RG` BIGINT NOT NULL,
  `Hospede_idHospede` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Hospede_idHospede`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) ,
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC) ,
  CONSTRAINT `fk_Pessoa_Fisica_Hospede1`
    FOREIGN KEY (`Hospede_idHospede`)
    REFERENCES `mydb`.`Hospede` (`idHospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa_Juridica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Juridica` (
  `CNPJ` BIGINT NOT NULL,
  `IE` BIGINT NOT NULL,
  `Hospede_idHospede` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Hospede_idHospede`),
  UNIQUE INDEX `IE_UNIQUE` (`IE` ASC) ,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) ,
  INDEX `fk_Pessoa_Juridica_Hospede1_idx` (`Hospede_idHospede` ASC) ,
  UNIQUE INDEX `Hospede_idHospede_UNIQUE` (`Hospede_idHospede` ASC) ,
  CONSTRAINT `fk_Pessoa_Juridica_Hospede1`
    FOREIGN KEY (`Hospede_idHospede`)
    REFERENCES `mydb`.`Hospede` (`idHospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `Hotel_idHotel` INT NOT NULL,
  `Hospede_idHospede` INT UNSIGNED NOT NULL,
  `valor_final` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Hotel1_idx` (`Hotel_idHotel` ASC) ,
  INDEX `fk_Reserva_Hospede1_idx` (`Hospede_idHospede` ASC) ,
  CONSTRAINT `fk_Reserva_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Hospede1`
    FOREIGN KEY (`Hospede_idHospede`)
    REFERENCES `mydb`.`Hospede` (`idHospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `valor_diaria` FLOAT UNSIGNED NOT NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) ,
  UNIQUE INDEX `nome_categoria_UNIQUE` (`nome_categoria` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Quarto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Quarto` (
  `idQuarto` INT NOT NULL,
  `numero` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idQuarto`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) ,
  INDEX `fk_Quarto_Categoria1_idx` (`Categoria_idCategoria` ASC) ,
  CONSTRAINT `fk_Quarto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `idtelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_telefone` BIGINT NOT NULL,
  PRIMARY KEY (`idtelefone`),
  UNIQUE INDEX `idtelefone_UNIQUE` (`idtelefone` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone_has_Hospede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`telefone_has_Hospede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`telefone_has_Hospede` (
  `telefone_idtelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Hospede_idHospede` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`telefone_idtelefone`, `Hospede_idHospede`),
  INDEX `fk_telefone_has_Hospede_Hospede1_idx` (`Hospede_idHospede` ASC) ,
  INDEX `fk_telefone_has_Hospede_telefone1_idx` (`telefone_idtelefone` ASC) ,
  CONSTRAINT `fk_telefone_has_Hospede_telefone1`
    FOREIGN KEY (`telefone_idtelefone`)
    REFERENCES `mydb`.`telefone` (`idtelefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_has_Hospede_Hospede1`
    FOREIGN KEY (`Hospede_idHospede`)
    REFERENCES `mydb`.`Hospede` (`idHospede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico_de_quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servico_de_quarto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servico_de_quarto` (
  `idservico_de_quarto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor_total` FLOAT NOT NULL,
  `Reserva_idReserva` INT NOT NULL,
  PRIMARY KEY (`idservico_de_quarto`),
  UNIQUE INDEX `idservico_de_quarto_UNIQUE` (`idservico_de_quarto` ASC) ,
  INDEX `fk_servico_de_quarto_Reserva1_idx` (`Reserva_idReserva` ASC) ,
  CONSTRAINT `fk_servico_de_quarto_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` FLOAT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico_de_quarto_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servico_de_quarto_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servico_de_quarto_has_produto` (
  `servico_de_quarto_idservico_de_quarto` INT UNSIGNED NOT NULL,
  `produto_idproduto` INT UNSIGNED NOT NULL,
  `quantidade` SMALLINT(4) UNSIGNED NOT NULL,
  `valor_unitario` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`servico_de_quarto_idservico_de_quarto`, `produto_idproduto`),
  INDEX `fk_servico_de_quarto_has_produto_produto1_idx` (`produto_idproduto` ASC) ,
  INDEX `fk_servico_de_quarto_has_produto_servico_de_quarto1_idx` (`servico_de_quarto_idservico_de_quarto` ASC) ,
  CONSTRAINT `fk_servico_de_quarto_has_produto_servico_de_quarto1`
    FOREIGN KEY (`servico_de_quarto_idservico_de_quarto`)
    REFERENCES `mydb`.`servico_de_quarto` (`idservico_de_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servico_de_quarto_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva_has_Quarto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva_has_Quarto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_has_Quarto` (
  `Reserva_idReserva` INT NOT NULL,
  `Quarto_idQuarto` INT NOT NULL,
  PRIMARY KEY (`Reserva_idReserva`, `Quarto_idQuarto`),
  INDEX `fk_Reserva_has_Quarto_Quarto1_idx` (`Quarto_idQuarto` ASC) ,
  INDEX `fk_Reserva_has_Quarto_Reserva1_idx` (`Reserva_idReserva` ASC) ,
  CONSTRAINT `fk_Reserva_has_Quarto_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Quarto_Quarto1`
    FOREIGN KEY (`Quarto_idQuarto`)
    REFERENCES `mydb`.`Quarto` (`idQuarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
